/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postgresqlproject;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author emreu
 */
public class AnaSayfa extends javax.swing.JFrame {

    /**
     * Creates new form AnaSayfa
     */
    public AnaSayfa() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Dernek İşlemleri");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnKurucularimiz = new javax.swing.JButton();
        btnDemirbaslar = new javax.swing.JButton();
        btnBursiyerler = new javax.swing.JButton();
        btnBurslarimiz = new javax.swing.JButton();
        btnKullaniciIslemleri = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnKurucularimiz.setText("KURUCULARIMIZ");
        btnKurucularimiz.setPreferredSize(new java.awt.Dimension(150, 150));
        btnKurucularimiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKurucularimizActionPerformed(evt);
            }
        });

        btnDemirbaslar.setText("DEMİRBAŞLAR");
        btnDemirbaslar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemirbaslarActionPerformed(evt);
            }
        });

        btnBursiyerler.setText("BURSİYERLERİMİZ");
        btnBursiyerler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBursiyerlerActionPerformed(evt);
            }
        });

        btnBurslarimiz.setText("BURSLARIMIZ");
        btnBurslarimiz.setMinimumSize(new java.awt.Dimension(150, 32));
        btnBurslarimiz.setPreferredSize(new java.awt.Dimension(150, 32));
        btnBurslarimiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBurslarimizActionPerformed(evt);
            }
        });

        btnKullaniciIslemleri.setText("KULLANICI İŞLEMLERİ");
        btnKullaniciIslemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullaniciIslemleriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(btnDemirbaslar, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(btnKullaniciIslemleri)
                        .addGap(283, 283, 283))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKurucularimiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(153, 153, 153)
                        .addComponent(btnBursiyerler, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBurslarimiz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKurucularimiz, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBursiyerler, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBurslarimiz, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKullaniciIslemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDemirbaslar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKurucularimizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurucularimizActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Kurucularimiz k = new Kurucularimiz();
        k.setVisible(true);
        
    }//GEN-LAST:event_btnKurucularimizActionPerformed

    private void btnBursiyerlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBursiyerlerActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BursiyerEkrani be = new BursiyerEkrani();
        be.setVisible(true);
    }//GEN-LAST:event_btnBursiyerlerActionPerformed

    private void btnKullaniciIslemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullaniciIslemleriActionPerformed
        // TODO add your handling code here:
        this.dispose();
        TumKullanicilar tk = new TumKullanicilar();
        tk.setVisible(true);
    }//GEN-LAST:event_btnKullaniciIslemleriActionPerformed

    private void btnBurslarimizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBurslarimizActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
        BursTakip burs = new BursTakip();
        burs.setVisible(true);
        
    }//GEN-LAST:event_btnBurslarimizActionPerformed

    private void btnDemirbaslarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemirbaslarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Demirbas d = new Demirbas();
        d.setVisible(true);
    }//GEN-LAST:event_btnDemirbaslarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                    
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AnaSayfa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AnaSayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBursiyerler;
    private javax.swing.JButton btnBurslarimiz;
    private javax.swing.JButton btnDemirbaslar;
    private javax.swing.JButton btnKullaniciIslemleri;
    private javax.swing.JButton btnKurucularimiz;
    // End of variables declaration//GEN-END:variables
}
