/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postgresqlproject;

import static postgresqlproject.ConnectionTest.getConnection;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author emreu
 */
public class BursTakip extends javax.swing.JFrame {

    /**
     * Creates new form BursTakip
     */
    ArrayList<Burs> burslar = new ArrayList<>();
    Connection conn = getConnection();
    DefaultTableModel dtm = new DefaultTableModel();
    String basliklar[] = {"Burs Id", "Tutar", "Verilme tarihi", "Baslangic Tarihi", "Bitiş Tarihi", "Bursiyer"};

    public BursTakip() {
        initComponents();
        this.setResizable(false);
        this.setTitle("Burs Takibi");
        dtm.setColumnIdentifiers(basliklar);
        bursSay();
        bursToplam();
        bursGoster();
        tblBurs.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBurs = new javax.swing.JTable();
        btnGeri = new javax.swing.JButton();
        btnSil = new javax.swing.JButton();
        btnGuncellle = new javax.swing.JButton();
        btnEkle = new javax.swing.JButton();
        lblToplamBursEtiket = new javax.swing.JLabel();
        lblToplamBurs = new javax.swing.JLabel();
        lblOdenenBursEtiket = new javax.swing.JLabel();
        lblOdenenToplam = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("BURS TAKİBİ");

        tblBurs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBurs);

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        btnSil.setText("Sil");
        btnSil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSilActionPerformed(evt);
            }
        });

        btnGuncellle.setText("Güncelle");
        btnGuncellle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncellleActionPerformed(evt);
            }
        });

        btnEkle.setText("Ekle");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        lblToplamBursEtiket.setText("Toplam Bursiyer Sayısı : ");

        lblToplamBurs.setText("0");

        lblOdenenBursEtiket.setText("Ödenen Burs Miktarı : ");

        lblOdenenToplam.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblOdenenBursEtiket)
                        .addGap(18, 18, 18)
                        .addComponent(lblOdenenToplam, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblToplamBursEtiket)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblToplamBurs, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGuncellle)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSil, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeri)
                    .addComponent(btnSil)
                    .addComponent(btnGuncellle)
                    .addComponent(btnEkle)
                    .addComponent(lblToplamBursEtiket)
                    .addComponent(lblToplamBurs))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOdenenBursEtiket)
                    .addComponent(lblOdenenToplam))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BursEkle be = new BursEkle();
        be.setVisible(true);
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AnaSayfa as = new AnaSayfa();
        as.setVisible(true);
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnGuncellleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncellleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BursGuncelle bg = new BursGuncelle();
        bg.setVisible(true);
    }//GEN-LAST:event_btnGuncellleActionPerformed

    private void btnSilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSilActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BursSil bg = new BursSil();
        bg.setVisible(true);
    }//GEN-LAST:event_btnSilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BursTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BursTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BursTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BursTakip.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BursTakip().setVisible(true);
            }
        });
    }

    public void bursGoster() {

        if (conn != null) {

            try {
                String sql = "select \"bursId\",burs.tutar,\"verilmeTarihi\",\"baslangicTarihi\",\"bitisTarihi\",bursiyerler.ad from burs inner join bursiyerler on \"burs\".\"bursiyer\" = \"bursiyerler\".\"bursiyerId\";";
                Statement s = conn.createStatement();
                ResultSet rs = s.executeQuery(sql);

                while (rs.next()) {

                    burslar.add(new Burs(rs.getInt("bursId"), rs.getInt("tutar"), rs.getString("verilmeTarihi"),
                            rs.getString("baslangicTarihi"), rs.getString("bitisTarihi"), rs.getString("ad")));
                }

                for (Burs burs : burslar) {

                    dtm.addRow(new Object[]{burs.getBursId(), burs.getTutar(), burs.getVerilmeTarihi(), burs.getBaslangicTarihi(), burs.getBitisTarihi(), burs.getBursiyer()});
                }
                conn.close();
                s.close();
                rs.close();
            } catch (SQLException ex) {
                Logger.getLogger(BursTakip.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    public void bursSay() {

        if (conn != null) {

            try {
                String selectSql = "select bursSayisi()";

                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    lblToplamBurs.setText(rs.getString("bursSayisi"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void bursToplam() {

        if (conn != null) {

            try {
                String selectSql = "select bursToplam()";

                Statement stmt = conn.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    lblOdenenToplam.setText(rs.getString("burstoplam"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGuncellle;
    private javax.swing.JButton btnSil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblOdenenBursEtiket;
    private javax.swing.JLabel lblOdenenToplam;
    private javax.swing.JLabel lblToplamBurs;
    private javax.swing.JLabel lblToplamBursEtiket;
    private javax.swing.JTable tblBurs;
    // End of variables declaration//GEN-END:variables
}
