/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postgresqlproject;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;
import static postgresqlproject.ConnectionTest.getConnection;

/**
 *
 * @author emreu
 */
public class BursiyerEkrani extends javax.swing.JFrame {

    /**
     * Creates new form BursiyerEkranii
     */
    private Connection con = getConnection();
    private DefaultTableModel dtm = new DefaultTableModel();
    private DefaultListModel dlm = new DefaultListModel();
    private ArrayList<Bursiyer> bursiyerler = new ArrayList<>();
    private String[] columns = {"Bursiyer Id", "Bursiyer No", "Ad", "Soyad", "Okul", "Bölüm", "Telefon", "Mail", "Baba adı", "Referans", "IBAN", "Köy", "İl", "İlçe"};
    private String insert = "INSERT INTO bursiyerler ( \"bursiyerNo\", ad, soyad, \"okul\", \"bolum\", \"telefon\", \"mail\", \"babaAdi\", \"referans\", \"iban\", \"koy\", il, ilce) \n"
            + "VALUES ( 123, 'Emre', 'Usta', 'FSMVÜ', 'Bilgisayar Mühendisliği', '05414919734', 'emreustaa34@gmail.com', 'Şaban','Kendisi','TR12154615541', 'Çatalca', 1,2 )";

    public BursiyerEkrani() {
        initComponents();
        this.setTitle("Bursiyer Ekranı");
        this.setResizable(false);
        listGuncellenenler.setModel(dlm);
        
        dtm.setColumnIdentifiers(columns);
        bursiyerGoruntule();
        tblBursiyerler.setModel(dtm);
        toplamBursiyerSayisi();
    }

    public void bursiyerGoruntule() {
        if (con != null) {

            try {
                String selectSql = "select \"bursiyerler\".\"bursiyerId\",\"bursiyerler\".\"bursiyerNo\",ad,soyad,okul,bolum,telefon,mail,\"babaAdi\",referans,iban,koy,il.isim as il,ilce.isim as ilce FROM bursiyerler INNER JOIN il on bursiyerler.il = \"il\".\"ilId\" INNER JOIN ilce on bursiyerler.ilce = \"ilce\".\"ilceId\"";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    System.out.println("Gelen ilçe : " + rs.getString("ilce"));
                    bursiyerler.add(new Bursiyer(rs.getInt("bursiyerId"), rs.getInt("bursiyerNo"), rs.getString("ad"), rs.getString("soyad"), rs.getString("okul"),
                            rs.getString("bolum"), rs.getString("telefon"), rs.getString("mail"), rs.getString("babaAdi"), rs.getString("referans"),
                            rs.getString("iban"), rs.getString("koy"), rs.getString("il"), rs.getString("ilce")));
                }
                for (Bursiyer bursiyer : bursiyerler) {

                    dtm.addRow(new Object[]{bursiyer.getBursiyerId(), bursiyer.getBursiyerNo(), bursiyer.getAd(),
                        bursiyer.getSoyad(), bursiyer.getOkul(), bursiyer.getBolum(), bursiyer.getTelefon(), bursiyer.getMail(),
                        bursiyer.getBabaAdi(), bursiyer.getReferans(), bursiyer.getIban(), bursiyer.getKoy(), bursiyer.getIl(), bursiyer.getIlce()});

                }
            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblBursiyerler = new javax.swing.JTable();
        btnGuncelle = new javax.swing.JButton();
        lblToplamBursiyerEtiket = new javax.swing.JLabel();
        lblToplamBursiyer = new javax.swing.JLabel();
        btnGeri = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listGuncellenenler = new javax.swing.JList<>();
        btnGoruntule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblBursiyerler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblBursiyerler);

        btnGuncelle.setText("Güncelle");
        btnGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuncelleActionPerformed(evt);
            }
        });

        lblToplamBursiyerEtiket.setText("Toplam Bursiyer Sayısı: ");

        lblToplamBursiyer.setText("0");

        btnGeri.setText("Geri");
        btnGeri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriActionPerformed(evt);
            }
        });

        jLabel1.setText("Güncellenen Bursiyerler");

        jScrollPane2.setViewportView(listGuncellenenler);

        btnGoruntule.setText("Görüntüle");
        btnGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGoruntuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblToplamBursiyerEtiket)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblToplamBursiyer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnGeri, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 961, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(137, 137, 137))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGoruntule, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(15, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuncelle)
                    .addComponent(lblToplamBursiyerEtiket)
                    .addComponent(lblToplamBursiyer)
                    .addComponent(btnGeri))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGoruntule)
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuncelleActionPerformed
        // TODO add your handling code here:
        this.dispose();
        BursiyerGuncelle bg = new BursiyerGuncelle();
        bg.setVisible(true);
    }//GEN-LAST:event_btnGuncelleActionPerformed

    private void btnGeriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AnaSayfa as = new AnaSayfa();

        as.setVisible(true);
    }//GEN-LAST:event_btnGeriActionPerformed

    private void btnGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGoruntuleActionPerformed
        // TODO add your handling code here:
        
        ArrayList veriler = new ArrayList();
        if (con != null) {

            try {
                String sql = "select * from guncellenen";

                Statement s = con.createStatement();
                ResultSet rs = s.executeQuery(sql);

                while (rs.next()) {

                    veriler.add("Eski Mail : " + rs.getString("eskiMail") + " - " + "Yeni Mail : " + rs.getString("yeniMail"));

                }

                for (int i = 0; i < veriler.size(); i++) {

                    dlm.addElement(veriler.get(i));

                }
            } catch (SQLException ex) {
                Logger.getLogger(TumKullanicilar.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnGoruntuleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BursiyerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BursiyerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BursiyerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BursiyerEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BursiyerEkrani().setVisible(true);
            }
        });
    }

    public void toplamBursiyerSayisi() {

        if (con != null) {

            try {
                String selectSql = "select bursiyerSayisi()";

                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    lblToplamBursiyer.setText(rs.getString("bursiyerSayisi"));
                }

            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }/*
     
     create or replace function bursiyersayisi()
returns integer as $toplam$
declare 
toplam integer;
begin
select count(*) into toplam from bursiyerler;
return toplam;
end;
$toplam$ language plpgsql;


     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeri;
    private javax.swing.JButton btnGoruntule;
    private javax.swing.JButton btnGuncelle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblToplamBursiyer;
    private javax.swing.JLabel lblToplamBursiyerEtiket;
    private javax.swing.JList<String> listGuncellenenler;
    private javax.swing.JTable tblBursiyerler;
    // End of variables declaration//GEN-END:variables
}
