/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postgresqlproject;

import java.awt.Image;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static postgresqlproject.ConnectionTest.getConnection;

/**
 *
 * @author emreu
 */
public class KullaniciGiris extends javax.swing.JFrame {

    /**
     * Creates new form KullaniciGiris
     */
    Connection con = getConnection();

    ArrayList<Kullanici> users = new ArrayList<>();

    public KullaniciGiris() {
        initComponents();

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/home.png")).getImage());
        this.setTitle("Kullanıcı Giriş Ekranı");
        this.setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserLogin = new javax.swing.JPanel();
        btnPersonelEkle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtKullaniciAdiGiris = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnCikis = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGiris = new javax.swing.JButton();
        txtSifreGiris = new javax.swing.JPasswordField();
        UserAdd = new javax.swing.JPanel();
        btnGeriiKullaniciEkle = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAdEkle = new javax.swing.JTextField();
        txtSoyadEkle = new javax.swing.JTextField();
        txtKullaniciAdiEkle = new javax.swing.JTextField();
        txtSifreEkle = new javax.swing.JTextField();
        txtIlEkle = new javax.swing.JTextField();
        txtIlceEkle = new javax.swing.JTextField();
        btnKaydet = new javax.swing.JButton();
        btnKullanicilariGoruntule = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        btnPersonelEkle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/kullaniciekleicon.png"))); // NOI18N
        btnPersonelEkle.setText(" Kullanici Ekle");
        btnPersonelEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPersonelEkleActionPerformed(evt);
            }
        });

        jLabel1.setText("Kullanıcı Adı : ");

        jLabel2.setText("Şifre : ");

        btnCikis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/cikis.png"))); // NOI18N
        btnCikis.setText("Çıkış");
        btnCikis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCikisActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/adaybeyaz.png"))); // NOI18N
        jLabel3.setAlignmentY(0.0F);
        jLabel3.setMaximumSize(new java.awt.Dimension(200, 73));

        jLabel4.setText("www.inovatifarge.com | argeinovatif@gmail.com");

        jLabel5.setText("Vakıf - Dernek Otomasyonu");

        btnGiris.setIcon(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/giris.png"))); // NOI18N
        btnGiris.setText("Giriş");
        btnGiris.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnGiris.setMaximumSize(new java.awt.Dimension(20, 20));
        btnGiris.setMinimumSize(new java.awt.Dimension(89, 44));
        btnGiris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGirisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserLoginLayout = new javax.swing.GroupLayout(UserLogin);
        UserLogin.setLayout(UserLoginLayout);
        UserLoginLayout.setHorizontalGroup(
            UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(UserLoginLayout.createSequentialGroup()
                        .addComponent(btnGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCikis, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(UserLoginLayout.createSequentialGroup()
                        .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(31, 31, 31)
                        .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtKullaniciAdiGiris, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(txtSifreGiris))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserLoginLayout.createSequentialGroup()
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UserLoginLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPersonelEkle))
                    .addGroup(UserLoginLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addGap(14, 14, 14))
        );
        UserLoginLayout.setVerticalGroup(
            UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserLoginLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(btnPersonelEkle)
                .addGap(18, 18, 18)
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtKullaniciAdiGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSifreGiris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCikis)
                    .addComponent(btnGiris, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        getContentPane().add(UserLogin, "card2");

        btnGeriiKullaniciEkle.setText("Geri");
        btnGeriiKullaniciEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeriiKullaniciEkleActionPerformed(evt);
            }
        });

        jLabel6.setText("Kullanıcı Bilgilerini Giriniz");

        jLabel7.setText("Ad :");

        jLabel8.setText("Soyad : ");
        jLabel8.setMaximumSize(new java.awt.Dimension(79, 16));
        jLabel8.setMinimumSize(new java.awt.Dimension(79, 16));

        jLabel9.setText("Kullanıcı Adı : ");

        jLabel10.setText("Şifre : ");

        jLabel11.setText("İl : ");

        jLabel12.setText("İlçe : ");

        txtSoyadEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoyadEkleActionPerformed(evt);
            }
        });

        txtKullaniciAdiEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKullaniciAdiEkleActionPerformed(evt);
            }
        });

        btnKaydet.setText("Kaydet");
        btnKaydet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaydetActionPerformed(evt);
            }
        });

        btnKullanicilariGoruntule.setText("Kullanıcıları Görüntüle");
        btnKullanicilariGoruntule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKullanicilariGoruntuleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout UserAddLayout = new javax.swing.GroupLayout(UserAdd);
        UserAdd.setLayout(UserAddLayout);
        UserAddLayout.setHorizontalGroup(
            UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAddLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserAddLayout.createSequentialGroup()
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIlceEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIlEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSifreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(UserAddLayout.createSequentialGroup()
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAdEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSoyadEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKullaniciAdiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(UserAddLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnGeriiKullaniciEkle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnKaydet, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, UserAddLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(btnKullanicilariGoruntule)
                        .addGap(16, 16, 16))))
            .addGroup(UserAddLayout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        UserAddLayout.setVerticalGroup(
            UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(UserAddLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGap(16, 16, 16)
                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(UserAddLayout.createSequentialGroup()
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAdEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoyadEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(UserAddLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSifreEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(UserAddLayout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtKullaniciAdiEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))))
                        .addGap(12, 12, 12))
                    .addGroup(UserAddLayout.createSequentialGroup()
                        .addComponent(btnKaydet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnGeriiKullaniciEkle)
                        .addGap(16, 16, 16)))
                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIlEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnKullanicilariGoruntule)
                    .addGroup(UserAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIlceEkle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(UserAdd, "card3");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeriiKullaniciEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeriiKullaniciEkleActionPerformed
        // TODO add your handling code here:
        UserLogin.setVisible(true);
        UserAdd.setVisible(false);

        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/home.png")).getImage());
        this.setTitle("Kullanıcı Giriş Ekranı");

    }//GEN-LAST:event_btnGeriiKullaniciEkleActionPerformed

    private void btnCikisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCikisActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCikisActionPerformed

    private void btnPersonelEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPersonelEkleActionPerformed
        // TODO add your handling code here:

        UserLogin.setVisible(false);
        UserAdd.setVisible(true);
        this.setTitle("Kullanıcı Ekle");
        this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/postgresqlproject/add.png")).getImage());
        //kullaniciEkle();

    }//GEN-LAST:event_btnPersonelEkleActionPerformed

    private void txtSoyadEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoyadEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoyadEkleActionPerformed

    private void txtKullaniciAdiEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKullaniciAdiEkleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKullaniciAdiEkleActionPerformed

    private void btnKullanicilariGoruntuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKullanicilariGoruntuleActionPerformed
        // TODO add your handling code here:

        TumKullanicilar allUsers = new TumKullanicilar();
        this.dispose();
        allUsers.setVisible(true);

    }//GEN-LAST:event_btnKullanicilariGoruntuleActionPerformed

    private void btnGirisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirisActionPerformed
        // TODO add your handling code here:
        String kullaniciAdi = txtKullaniciAdiGiris.getText().toString();
        String sifre = txtSifreGiris.getText().toString();
        boolean iceriyorMu = false;

        if (con != null) {

            try {
                String selectSql = "select \"kullaniciId\",kullanici.ad,kullanici.soyad,\"kullaniciAdi\",kullanici.sifre,il.isim as il,ilce.isim as ilce from kullanici inner join il on kullanici.il = \"il\".\"ilId\" INNER JOIN ilce on kullanici.ilce = \"ilce\".\"ilceId\"";

                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    if (kullaniciAdi.contains(rs.getString("kullaniciAdi")) && sifre.contains(rs.getString("sifre"))) {

                        iceriyorMu = true;

                    }
                    if (!kullaniciAdi.contains(rs.getString("kullaniciAdi")) && !sifre.contains(rs.getString("sifre"))) {
                        iceriyorMu = false;

                    }

                }

                if (iceriyorMu == true) {
                    AnaSayfa bursiyer = new AnaSayfa();
                    this.dispose();
                    bursiyer.setVisible(true);
                    System.out.println("Kullanıcı Girişi Başarılı!");
                } else {
                    System.out.println("Eşit değil");
                    JOptionPane.showMessageDialog(this, "Bilgileriniz hatalı lütfen kontrol ediniz!");
                }

            } catch (SQLException ex) {

                JOptionPane.showMessageDialog(this, "Hata : " + ex);
                //Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        txtKullaniciAdiGiris.setText("");
        txtSifreGiris.setText("");

    }//GEN-LAST:event_btnGirisActionPerformed

    private void btnKaydetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaydetActionPerformed
        // TODO add your handling code here:

        if (txtAdEkle.getText().equals("") || txtSoyadEkle.getText().equals("")
                || txtKullaniciAdiEkle.getText().equals("") || txtSifreEkle.getText().equals("")
                || txtIlEkle.getText().equals("") || txtIlceEkle.getText().equals("")) {

            JOptionPane.showMessageDialog(this, "Lütfen Girdiğiniz Bilgileri Kontrol Ediniz");

        } else {

            String ad = txtAdEkle.getText().toString();
            String soyad = txtSoyadEkle.getText().toString();
            String kullaniciAdi = txtKullaniciAdiEkle.getText().toString();
            String sifre = txtSifreEkle.getText().toString();
            int il = Integer.valueOf(txtIlEkle.getText().toString());
            int ilce = Integer.valueOf(txtIlceEkle.getText().toString());

            kullaniciEkle(ad, soyad, kullaniciAdi, sifre, il, ilce);
            System.out.println("Kullanıcı ekleme işlemi başarılı..!");
        }


    }//GEN-LAST:event_btnKaydetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KullaniciGiris.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KullaniciGiris().setVisible(true);
            }
        });
    }

    public void getUser() {

        if (con != null) {

            try {
                String selectSql = "SELECT * FROM kullanici";

                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(selectSql);

                while (rs.next()) {

                    users.add(new Kullanici(rs.getInt("kullaniciId"), rs.getString("ad"), rs.getString("soyad"), rs.getString("kullaniciAdi"), rs.getString("sifre"), rs.getString("il"), rs.getString("ilce")));

                }
                for (Kullanici user : users) {
                    System.out.println("KULLANICI ID : " + user.getKullaniciId());
                    System.out.println("KULLANICI AD : " + user.getAd());
                    System.out.println("KULLANICI SOYAD : " + user.getSoyad());
                    System.out.println("KULLANICI KULLANICI ADI : " + user.getKullaniciAdi());
                    System.out.println("KULLANICI ŞİFRE : " + user.getSifre());
                    System.out.println("KULLANICI İLÇE : " + user.getIlce());
                    System.out.println("KULLANICI İL : " + user.getIl());
                }
            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }

    public void kullaniciEkle(String ad, String soyad, String kullaniciAdi, String sifre, int il, int ilce) {

        Connection con = getConnection();

        if (con != null) {

            try {
                String kullaniciSql = "Select * FROM kullanici";
                Statement stmt = con.createStatement();
                ResultSet rs = stmt.executeQuery(kullaniciSql);
                while (rs.next()) {

                    if (!rs.getString("kullaniciAdi").equals(kullaniciAdi)) {

                        String insertSql = "INSERT INTO kullanici (\"ad\",\"soyad\",\"kullaniciAdi\",\"sifre\",il,ilce) VALUES ('" + ad + "',"
                                + "'" + soyad + "',"
                                + "'" + kullaniciAdi + "',"
                                + "'" + sifre + "',"
                                + il + "," + ilce + ")";

                        /* Sorgu çalıştırma *****/
                        stmt.executeUpdate(insertSql);

                        con.close();

                        stmt.close();
                        break;

                    } else {
                        JOptionPane.showMessageDialog(this, "Girmiş olduğunuz kullanıcı adı sistemde yer almaktadır.");
                        break;
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(KullaniciGiris.class.getName()).log(Level.SEVERE, null, ex);
            }


            /*Bağlantı sonlandırma *****/
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel UserAdd;
    private javax.swing.JPanel UserLogin;
    private javax.swing.JButton btnCikis;
    private javax.swing.JButton btnGeriiKullaniciEkle;
    private javax.swing.JButton btnGiris;
    private javax.swing.JButton btnKaydet;
    private javax.swing.JButton btnKullanicilariGoruntule;
    private javax.swing.JButton btnPersonelEkle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAdEkle;
    private javax.swing.JTextField txtIlEkle;
    private javax.swing.JTextField txtIlceEkle;
    private javax.swing.JTextField txtKullaniciAdiEkle;
    private javax.swing.JTextField txtKullaniciAdiGiris;
    private javax.swing.JTextField txtSifreEkle;
    private javax.swing.JPasswordField txtSifreGiris;
    private javax.swing.JTextField txtSoyadEkle;
    // End of variables declaration//GEN-END:variables
}
